### ISSUE TITLE
開催予定のイベントとスケジュールを知りたい

### ISSUE THREAD

**Issue by Saki-htr** [teacherteacher-jp/manabiya#100]
# 困っていること
- コミュニティでのイベント開催は、色んなチャンネル・スレでどんどん企画されているので、どんなイベントが開催予定なのかの把握や、スケジュール管理が大変。
- TTのdiscordサーバーは、ロールによっていくつかのカテゴリに分かれているので、Manabiyaの登録者にだけイベントのお知らせが見れるようにしたい。しかしDiscordのイベント機能は、discordの参加者全員に表示されてしまうので使えない。

## issueのゴール
- 直近で作る機能を決める
- 必要なデータ型(どんなmigrationファイルを実行するか)を決める

**Comment by Saki-htr** [comment]
# 直近で作る機能

イベント機能が必要なのは、「開催予定のイベントとスケジュールを知りたい」が一番の理由なので、イベントのCRUD機能だけをまず作ってリリースする。

## 必要なデータ
- イベントの名前(title)
- 開催概要(description)
- 開始時刻

## 今回は作らないデータ
- 主催者が誰か
- 参加者が誰か

**Comment by juneboku** [comment]
「会場」を表すカラムもあるとよさそう、と思いました！
どういう型で表現するかは相談しながら見つけていきたいです :muscle:

**Comment by Saki-htr** [comment]
たしかにいざ参加したい!ってなった時に場所が分からないと不親切ですね。イベント情報チャンネル見たら、オンラインの場合「どこのボイスチャンネルでやるか」も決めてたので、追加しました!

**Comment by juneboku** [comment]
ここまで話した内容で、実装を進めてもらって大丈夫そうです :ok_person:

**Comment by Saki-htr** [comment]
# データの名前と型

```ruby
class CreateEvents < ActiveRecord::Migration[7.0]
  def change
    create_table :events do |t|
      t.string :title, null: false
      t.text :description, null: false
      t.timestamptz :start_time, null: false
      t.string :venue, null: false

      t.timestamps

      t.index :start_time  # 一覧ページで開催時刻を元にソートするのでインデックスをはる
    end
  end
end
```

※補足
- 開催時刻のデータ型： 海外に在住の方もいらっしゃるので、日本時間のみでなく海外のタイムゾーンにも対応した方が良いと考え、`timestamptz`にしました。
- 会場のデータ名：会場を表す英語として、他にlocationはどうかと思いましたが、venueはイベントの開催地・会場を指し、locationは特定の場所や地点を指すので、 venueにしました。
- venueのデータ型: 会場をセレクトできた方が便利かと思い、Eventテーブルとは別にVenueテーブルを作って、 Venue : Event = 1 : 多 の関連付けをして〜というのを考えましたが、 「オンラインだけでなくオフラインでやる場合もあるので、3つのボイスチャンネルのどれかで開催されるとは限らない」「コードの複雑さに対して得られるメリットが少ない」と思ったので、String型にして、ユーザーに入力してもらおうと思っています。

**Comment by juneboku** [comment]
### title

- stringよさそう
- 最大長は100くらいあれば足りるかなあ

### description

- 最大長どうしましょうかねえ、それによってはstringになるかも
- 必ず書いてもらう、ってことで `null: false` でいい気がする

### start_time

https://github.com/teacherteacher-jp/manabiya/blob/8b6f9007f9c067ef1ef85d0896c6fbd9ae17fa64/db/migrate/20240923054720_add_server_joined_at_column_to_members_table.rb#L3

```rb
manabiya(dev)> Member.first
  Member Load (4.0ms)  SELECT "members".* FROM "members" ORDER BY "members"."id" ASC LIMIT 1 /*application='Manabiya'*/
=>
#<Member:0x00000001215b9038
 id: 1,
 name: "juneboku",
 icon_url: "https://cdn.discordapp.com/avatars/107565503145130...",
 discord_uid: "107565503145130...",
 created_at: "2024-06-24 21:27:31.301305000 +0900",
 updated_at: "2024-11-10 23:17:20.194757000 +0900",
 server_joined_at: "2023-10-30 23:10:17.578000000 +0900",
 admin: true>
```

- Memberモデルのserver_joined_atはdatetimeでつくりました
  - タイムゾーンも入っているしこれで事足りると思います！
- indexをはっておきたいですね、賛成です

### venue

- カラム名、よさそう
- integerにしてenumにする案も考えていたけれど、stringで自由記述って形でスタートするのに賛成です
  - どんなものが入力されるのか観察して、そのあとの展開を考えたい

**Comment by Saki-htr** [comment]
> title
> 最大長は100くらいあれば足りるかなあ

文字数制限のこと抜けてました! たしかに設定した方が良いですね。 
イベント情報チャンネルを見てると、会の名前は長くても25文字くらいだったので、 titleはもっと少なく50文字でも良いのではと思っています。それ以上長いとイベントの概要が分かりにくい名前になってそうと思うので、イベント作成者の方に**50文字**でイベント内容を要約していただいてタイトル名に入れてもらうのが良さそうに思っています。

> description
> 最大長どうしましょうかねえ、それによってはstringになるかも

なんとなくtext型にしてしまってたんですが、 text型だと文字数制限がなく1GB分のデータ(5~6億文字分)を保存できてしまうんですね! これは too muchなので、文字数制限が設定できるstring型の方が適切と考えました。
文字数は**1000文字**もあれば十分かなと思いますが、どうでしょうか?? (ちなみに東京懇親会の開催概要は250文字、一番長い「お話会のお知らせ」で717文字でした)

> 必ず書いてもらう、ってことで null: false でいい気がする

そうですね、イベント作成してる時点で「こういうことやりたい」というのがある程度作成者の中にあると思うので、必須で入力していただいて、後から更新していただければ良いかなと思ってます。むしろ任意にして入力漏れがある方がもったいないなと思ってます〜


> venue
> integerにしてenumにする案も考えていたけれど、stringで自由記述って形でスタートするのに賛成です
> どんなものが入力されるのか観察して、そのあとの展開を考えたい

はい! 私もリリースして観察してからベストな形を目指していくので良いと思います!

**Comment by juneboku** [comment]
- title
  - たしかに50文字もあれば足りそう、よさそう
- description
  - 「イベント一覧」が表示されるビューを想定したときに、改行ナシで300文字くらいにおさまっていると見やすそうと思った
  - 「お話会のお知らせ」のようにしっかり書いてあるやつは、別途でlink的なカラムを用意して一次情報を参照してあげるといいのかも、と思うに至りました
- venue
  - カラム名もデータ型もこれで進めてみましょ〜

**Comment by Saki-htr** [comment]
# started_at のデータ型どうする問題について、今の結論

> Memberモデルのserver_joined_atはdatetimeでつくりました
タイムゾーンも入っているしこれで事足りると思います！

- Rails側でdatetimeと指定すると、 postgresqlの方ではデフォルトではタイムゾーンのデータは入らない。でもRailsの `config/application.rb`で `config.time_zone = "Asia/Tokyo"`と指定することで、 データにタイムゾーンの情報を入れてくれる。

```ruby
 Member.first.server_joined_at
  Member Load (33.8ms)  SELECT "members".* FROM "members" ORDER BY "members"."id" ASC LIMIT 1 /*application='Manabiya'*/
=> 2024-11-11 15:41:38.664000000 JST +09:00 # 「JST +09:00」がタイムゾーン情報
```

- これを元に海外在住の方のPC,スマホ(クライアント側)のタイムゾーンを元に表示される時刻を変える実装をcursorに聞いたら、JS使って結構一瞬ではいかなそうだった。
- 結論
  - 現在、海外在住のユーザー の方は少なく、ほぼ日本在住のユーザー。
  - 海外在住のユーザー の一人が、「時差の計算に慣れてるので大丈夫です」とおっしゃってくださってる
  - これを実装するメリットより、日本時間にだけ対応して早くリリースする方が良いと判断した。

**Comment by juneboku** [comment]
started_at という命名案が登場したと思うので、コメントしておきます！

- 過去のある時点でのなにかを時刻を記録するなら
  - joined_at とか finished_at とか、過去形の名前にする
- 未来の予定としての時刻を記録するなら
  - start_at とか expire_at とか、現在形の名前にする

ぼくはこんなふうに使い分けています！今回は「未来」の方なので、動詞の過去形にしない方がいいと考えました。

**Comment by Saki-htr** [comment]
> started_at という命名案

最初 start_time にしていたのに途中から無意識に started_at に変えてしまってました...
**`start_at`にしようと思います~**

- start_timeだと、"時刻"のデータだけ入ってるように勘違いさせてしまう。本当は年日付のデータも入っているので不適切
- started_atだと、おっしゃる通り、過去の時点の時刻を記録する意味合いになるので、不適切。
- 今回は「これからこの日のこの時間にイベントが開催されるよ」という未来の予定の時刻を記録するので、 `start_at`にしようと思います~

**Comment by Saki-htr** [comment]
# descriptionカラムについてじゅーんさんと話して決めたこと
### 1. viewでのコード：シンプルに `<%= @event.description %> `と書いて表示させる
  - 当初私が、「イベントの開催概要の情報を、discordでなく、Manabiyaのイベント詳細画面の開催概要(description)に書いてもらって情報を集約した方がユーザーが使いやすい」と思っていた。が、  Railsのviewにそのまま`<%= @event.description %> `と書くと、リンクを入力した際自動的にリンク化してくれなかったり、改行して表示してくれないことに気づいてなかった。
  - discordやXみたいに書きやすく読みやすいtextareaにするには、実装がひと頑張り必要になる。
  - ユーザーの一番の困りごとは、 開催予定のイベントの把握なので、これは省いてリリースのスピードを早める方を優先すべき。
  - なので、タイトルには収まりきらない、ちょっとした概要を書くところにする。
### 2. 文字数上限：200文字にする
- 改行もマークダウンも自動リンク化もできないので、文字数が多いと読む人も書く人も辛い。GPTに200文字, 300文字, 400文字の文章を書いてみてもらった結果、300文字だと結構読むのがしんどく感じるので、200文字にすることにした。
<details><summary>GPTに聞いた時のスクショ</summary>

![image (1)](https://github.com/user-attachments/assets/f707a4cc-4aec-4d1e-b669-6efcb1c41abd)
![image２ (1)](https://github.com/user-attachments/assets/b5ff0148-60a4-45c2-a173-bb6c27493bd9)

</details>

### 3. Eventモデルに新たに、「discordのイベントの一次情報にとべるリンク」を入れるカラムを追加する
https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2480248856

> 「お話会のお知らせ」のようにしっかり書いてあるやつは、別途でlink的なカラムを用意して一次情報を参照してあげるといいのかも、と思うに至りました

- ファーストリリースでは参加者登録の機能をつけないので、ユーザーがManabiyaのイベント一覧を見た時に、「このイベント参加したい!」となっても「discordで、イベント概要が書かれてる場所を自分で探して、そこで行きたいとコメントしないと申し込めない」のはかなり体験が悪いと思ったので、最初のリリースで付けたいと思った。 
- 今後、参加者登録機能ができた後も、イベントの詳細を詰めたりコメントしあうのは、discordの方が体験が良いので、discordのリンクはずっとあった方がよさそう

**Comment by Saki-htr** [comment]
# 2回目のマイグレーションファイル レビュー依頼
## データの名前と型

<details><summary>1回目の案</summary>

```ruby
class CreateEvents < ActiveRecord::Migration[7.0]
  def change
    create_table :events do |t|
      t.string :title, null: false
      t.text :description, null: false
      t.timestamptz :start_time, null: false
      t.string :venue, null: false

      t.timestamps

      t.index :start_time  # 一覧ページで開催時刻を元にソートするのでインデックスをはる
    end
  end
end
```
</details>


```ruby
class CreateEvents < ActiveRecord::Migration[7.0]
  def change
    create_table :events do |t|
      t.string :title, null: false
      t.text :description, null: false
      t.datetime :start_at, null: false
      t.string :venue, null: false
      t.string :discord_link, null: false

      t.timestamps

      t.index :start_at  # 一覧ページで開催時刻を元にソートするのでインデックスをはる
    end
  end
end
```

## 1回目の案との変更点
- `start_time`→`start_at`に変更(https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2480276543より)
- `t.timestamptz`→`t.datetime`に変更(https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2480261749より)
- イベントの一次情報のリンクを入れるカラムの追加 (https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2481211970 より)
  - データ型： 今のdiscordのコメントのリンクが88文字で、Railsのstring型は最大255文字数なのでstring型で十分足りると思ってます。
  - カラム名： イベントの一時情報であることを示す名前も盛り込んだ方が良いかと思いましたが、イベントの一次情報以外にdiscrodのリンクを貼るケースが今のところは考えにくいので、 そのまま `discord_link`にしました。
  - `null: false`： discordで話す前にmanabiyaでイベント作成する場合、入力必須だと不便かなとも思ったのですが、入力漏れがあってスレを見つけられない方がコミュニティにとって不利益だと思うので、入力必須にしました。 

## 実装するバリデーション

- `title`:50文字(https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2480248856より)
- `description`:200文字 (https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2481211970より)
- `venue`: 50文字 (titleと同じくらいで十分かなと思いました)
- `discord_link`： discordのリンクは `https://discord.com/channels/<サーバーid>/<チャンネルid>/<メッセージid>`で構成されてるので、入力時に`https://discord.com/channels/<サーバーid>`が合ってるかバリデーションを入れようと思います。/ 文字数のバリデーションはつけない予定

**Comment by juneboku** [comment]
ありがとうございます！だいぶ仕上がってきましたね :blush:

- discord_link
  - Discord に限定するか否かを考えて、気持ちは「URLなんでも登録できてよさそう」寄りです
  - イベント情報がまとまっているページが Notion でも Google Docs でも、積極的にそれの入力を弾く理由はなさそうな？
  - TT に関するスケジュールとして、こういう URL https://reseed.resemom.jp/article/2024/11/21/9842.html とともに Manabiya に登録されるのは悪いことではなさそう
- 他のカラム
  - よさそう！ :clap:

**Comment by Saki-htr** [comment]
> イベント情報がまとまっているページが Notion でも Google Docs でも、積極的にそれの入力を弾く理由はなさそうな？
TT に関するスケジュールとして、こういう URL https://reseed.resemom.jp/article/2024/11/21/9842.html とともに Manabiya に登録されるのは悪いことではなさそう

たしかにです、 イベントはdiscordでのお知らせ以外にも、一次情報となるリンクがたくさんあるのですね。
それならdiscordのリンクに限定しない方が良いですし、バリデーションも必要ないですね。


https://github.com/teacherteacher-jp/manabiya/issues/100#issuecomment-2495768327 に反映しました!

**Comment by juneboku** [comment]
source_link よさそうです！

**Comment by Saki-htr** [comment]
ありがとうございます! データ型決まったのでこれから実装入ります💪
